-- MySQL Script generated by MySQL Workbench
-- Seg 14 Nov 2016 15:58:45 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema memorize
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema memorize
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `memorize` DEFAULT CHARACTER SET utf8 ;
USE `memorize` ;

-- -----------------------------------------------------
-- Table `memorize`.`assunto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `memorize`.`assunto` (
  `id` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `memorize`.`area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `memorize`.`area` (
  `id` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `assunto_id` INT NOT NULL,
  PRIMARY KEY (`id`, `assunto_id`),
  INDEX `fk_area_assunto1_idx` (`assunto_id` ASC),
  CONSTRAINT `fk_area_assunto1`
    FOREIGN KEY (`assunto_id`)
    REFERENCES `memorize`.`assunto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `memorize`.`pergunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `memorize`.`pergunta` (
  `id` INT NOT NULL,
  `conteudo` VARCHAR(255) NOT NULL,
  `qtd_jogadas` INT NULL,
  `qtd_erros` INT NULL,
  `area_id` INT NOT NULL,
  PRIMARY KEY (`id`, `area_id`),
  INDEX `fk_pergunta_area1_idx` (`area_id` ASC),
  CONSTRAINT `fk_pergunta_area1`
    FOREIGN KEY (`area_id`)
    REFERENCES `memorize`.`area` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `memorize`.`resposta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `memorize`.`resposta` (
  `id` INT NOT NULL,
  `conteudo` VARCHAR(255) NOT NULL,
  `correta` TINYINT(1) NULL,
  `pergunta_id` INT NOT NULL,
  PRIMARY KEY (`id`, `pergunta_id`),
  INDEX `fk_resposta_pergunta_idx` (`pergunta_id` ASC),
  CONSTRAINT `fk_resposta_pergunta`
    FOREIGN KEY (`pergunta_id`)
    REFERENCES `memorize`.`pergunta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
